export default async function fetchPools() {
    return [
        {
            id: "profit-sharing",
            displayName: "Profit Sharing",
            tokenForLogo: 'FARM',
            state: 0,
            rewardAPY: 95.66,
            collateralTokenSymbols: 'FARM',
            rewardTokenSymbols: 'FARM',
        },
        {
            id: 'weth-farm',
            displayName: "WETH Farm",
            tokenForLogo: 'ETH',
            state: 0,
            rewardAPY: 92.16,
            collateralTokenSymbols: 'fWETH',
            rewardTokenSymbols: 'FARM',
        },
        {
            id: "usdc-farm",
            displayName: "USDC Farm",
            tokenForLogo: 'USDC',
            state: 0,
            rewardAPY: 26.61,
            collateralTokenSymbols: 'fUSDC',
            rewardTokenSymbols: 'FARM',
        },
        {
            id: "dai-farm",
            displayName: "DAI Farm",
            tokenForLogo: 'DAI',
            state: 0,
            rewardAPY: 60.92,
            collateralTokenSymbols: 'fDAI',
            rewardTokenSymbols: 'FARM',
        },
        {
            id: "usdt-farm",
            displayName: "USDT Farm",
            tokenForLogo: 'USDT',
            state: 0,
            rewardAPY: 29.03,
            collateralTokenSymbols: 'FARM',
            rewardTokenSymbols: 'FARM',
        },
        {
            id: "wbtc-farm",
            displayName: "WBTC Farm",
            tokenForLogo: 'WBTC',
            state: 0,
            rewardAPY: 32.10,
            collateralTokenSymbols: 'fWBTC',
            rewardTokenSymbols: 'FARM',
        },
        {
            id: "renbtc-farm",
            displayName: "RENBTC Farm",
            tokenForLogo: 'REN',
            state: 0,
            rewardAPY: 34.44,
            collateralTokenSymbols: 'fRENBTC',
            rewardTokenSymbols: 'FARM',
        },
        {
            id: "crvrenbtc-farm",
            displayName: "CRVRENBTC Farm",
            tokenForLogo: 'CRVRENWBTC',
            state: 0,
            rewardAPY: 43.89,
            collateralTokenSymbols: 'fCRVRENWBTC',
            rewardTokenSymbols: 'FARM',
        },
        {
            id: "balancer-farm-v2",
            displayName: "Balancer Farm V2",
            tokenForLogo: '⚖️',
            state: 1,
            rewardAPY: null,
            collateralTokenSymbols: 'BPT 20/80',
            rewardTokenSymbols: 'FARM',
        },
        {
            id: "balancer-farm-v1",
            displayName: "Balancer Farm V1",
            tokenForLogo: '⚖️',
            state: 1,
            rewardAPY: null,
            collateralTokenSymbols: 'BPT 5/95',
            rewardTokenSymbols: 'FARM',
        },
        {
            id: "profit-sharing",
            displayName: "Profit Sharing V1",
            tokenForLogo: '🧧',
            state: 1,
            rewardAPY: null,
            collateralTokenSymbols: 'FARM',
            rewardTokenSymbols: 'DAI',
        }
    ];
}